### PR TITLE
Feature/update municipality

### PR DESCRIPTION
**Pull request by Doud63**

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Hello,
You can take the opportunity to fix the issue #7.

**Comment by gmichard** [comment]
#7 fixed by 02eb1d0

**Comment by gillesbourgeat** [comment]
:+1:

**Comment by gmichard** [comment]
Previously you have force `zipcode` and `id` to begin by 0" : see c4d6db2
You can see difference between [before](https://raw.githubusercontent.com/thelia-modules/INSEEGeo/bf07aab17f412ce50d90d112762af1fc7e06f1a8/Config/insert_city_0.sql) and [after](https://raw.githubusercontent.com/thelia-modules/INSEEGeo/c4d6db2bdd668096df796cd9d1d55bc6d1000f32/Config/insert_city_0.sql) with `insert_city_0.sql` example file.

So, references to `insee_geo_municipality`.`id` can be broken.
**There is some issue to solved ?**

**Pull request merged**
